FIRST_INVENTORY_POSITION = (471, 1056)
INVENTORY_SPACING = (48, 0)
HAND_INVENTORY_POSITION = (1278, 1056)
# pick up duration also accounts for the 1 second delay
PICK_UP_DURATION = 2.5
PICK_UP_STOP_DURATION = 1
PICK_UP_HOVER_DURATION = .75
RUN_DURATION = 0.1
CRAFT_KEYPRESS_DURATION = 0.25
KEYPRESS_DURATION = 0.2
FINISH_CRAFTING_DURATION = 1
MOUSE_CLICK_DURATION = 0.05
